# .github/workflows/deploy.yml (The Definitive Fix)

name: Deploy Project to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Execute deployment script
        working-directory: ${{ github.workspace }}
        env:
          MASTER_PASSWORD: ${{ secrets.MASTER_PASSWORD }}
        run: |
          bash ./execute.sh
