# .github/workflows/deploy.yml (The Definitive Fix)

name: Deploy Project to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Execute deployment script
        working-directory: ${{ github.workspace }}
        env:
          MASTER_PASSWORD: ${{ secrets.MASTER_PASSWORD }}
        run: |
          bash ./execute.sh

      # --- THE GUARANTEED CLEANUP FIX ---
      - name: 3. Force Workspace Cleanup
        # This step runs whether Step 2 succeeded or failed.
        if: always()
        # It runs in the same directory as the script.
        working-directory: ${{ github.workspace }}
        # It uses sudo to forcefully remove all files, regardless of who owns them.
        run: |
          echo "Forcibly cleaning up workspace..."
          sudo rm -rf .
