# .github/workflows/deploy.yml (Simplified for Self-Hosted Runner)

name: Deploy Project to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # This is the magic line. It tells GitHub to run this job on your VM.
    runs-on: self-hosted
    
    steps:
      - name: 1. Checkout Repository
        # The runner will check out a copy of the code into its working directory.
        uses: actions/checkout@v4

      - name: 2. Execute deployment script locally
        working-directory: ${{ github.workspace }}
        # The runner is already on the correct machine, so we just run the script.
        # We still pass the MASTER_PASSWORD as a secret.
        env:
          MASTER_PASSWORD: ${{ secrets.MASTER_PASSWORD }}
        run: |
          sudo bash ./execute.sh
